apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-managment-config-for-kubernetes
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: operators/identity-configuration-management-for-kubernetes
    repoURL: 'https://github.com/identitatem/idp-mgmt-gitops'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
