apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: idp-mgmt-config
  namespace: idp-mgmt-config
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetNamespaces:
  - idp-mgmt-config
