apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: primary-authrealm-placement
  namespace: idp-mgmt-config
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          authdeployment: primary